CREATE DATABASE  IF NOT EXISTS LEAGUECHAMPS;
USE LEAGUECHAMPS;

DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS USER_LOGIN;
DROP TABLE IF EXISTS TEAMS;
DROP TABLE IF EXISTS MATCHES;

CREATE TABLE IF NOT EXISTS USERS (
username varchar(20),
first_name varchar(50) NOT NULL,
last_name varchar(50) NOT NULL,
CONSTRAINT users_username_PK PRIMARY KEY (username)
) ENGINE=InnoDB;
 
CREATE TABLE IF NOT EXISTS USER_LOGIN (
username varchar(20),
password char(40) NOT NULL,
CONSTRAINT userlogin_username_PK PRIMARY KEY (username),
CONSTRAINT userlogin_username_FK FOREIGN KEY (username) REFERENCES USERS(username)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS TEAMS (
TEAM_ID varchar(4),
TEAM_NAME varchar(50) UNIQUE NOT NULL,
PHOTO varchar(50) NOT NULL,
CONSTRAINT team_teamid_PK PRIMARY KEY (TEAM_ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS MATCHES (
MATCH_NUMBER int(11),
HOME_TEAM varchar(50) NOT NULL,
AWAY_TEAM varchar(50) NOT NULL,
VENUE varchar(50) NOT NULL,
DATE DATE NOT NULL,
TIME TIME NOT NULL,
CONSTRAINT matches_matchnumber_PK PRIMARY KEY (MATCH_NUMBER),
CONSTRAINT matches_hometeam_FK FOREIGN KEY (HOME_TEAM) REFERENCES TEAMS(TEAM_ID),
CONSTRAINT matches_awayteam_FK FOREIGN KEY (AWAY_TEAM) REFERENCES TEAMS(TEAM_ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS BETS (
MATCH_NUMBER int(11) NOT NULL,
username varchar(20) NOT NULL,
BET varchar(50) NOT NULL,
CONSTRAINT bets_matchnumber_username_PK PRIMARY KEY (MATCH_NUMBER, username),
CONSTRAINT bets_bet_FK FOREIGN KEY (BET) REFERENCES TEAMS(TEAM_ID),
CONSTRAINT bets_matchnumber_FK FOREIGN KEY (MATCH_NUMBER) REFERENCES MATCHES(MATCH_NUMBER),
CONSTRAINT bets_username_FK FOREIGN KEY (username) REFERENCES USERS(username)
) ENGINE=InnoDB;